import os
basedir = os.path.abspath(os.path.dirname(__file__))

bearer_tokens = {
    "SUPER" : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJlNmkyNTd5ejdsVHU4Qnk2ZmhlYSJ9.eyJpc3MiOiJodHRwczovL2xlYXJuaW5nLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVmZDA0Njc4YzUxMDYwMDA3MmE1ZGFkYSIsImF1ZCI6Imh0dHBzOi8vcG9ja2llLWFwaSIsImlhdCI6MTYwNzU2NjYzNCwiZXhwIjoxNjA3NjUzMDM0LCJhenAiOiJ0QWZwSHFENHNnZVJlMDdxQVoyMFpnQlU0M0tTU0RkZiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOnVzZXIiLCJyZWFkOnVzZXIiLCJyZWFkOnVzZXJzIl19.MuMyrIVVTLEHzwW--dmpjaV5oen7GQpiL2IIcSV8Gbp7KSImbvR6SkM_JgJ2i5U0qpIpxCqGudF508mAaaz3AodKYEcX1zO9qYC7fworElIaH4tOHHFIy9Mm0_cDVzl8l8voVn-SxscvSNqQzv1oAT9L_xHKQf7KmbUE_H7vvjFdXbNp3R4097VRkoUAUKMnSW3ZAgwO1ty_P5K0JjVOLK5-iumwCUJ_Rl82L6ETI_A0nuAnkTwZjlv-ht6V2T2F9d6V1cxNTlrusMHQW3-RfJYwHySRjxnmavGjl-6J7gJyoaKf_wzcDw44UxaC09dFm-kpt5O6_t5jfksTmZHnsQ",
    "BASIC": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImJlNmkyNTd5ejdsVHU4Qnk2ZmhlYSJ9.eyJpc3MiOiJodHRwczovL2xlYXJuaW5nLWF1dGguZXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDVmZDAzZmYxZTNiMDRiMDA3NmExM2ZlYyIsImF1ZCI6Imh0dHBzOi8vcG9ja2llLWFwaSIsImlhdCI6MTYwNzU2Njc1MCwiZXhwIjoxNjA3NjUzMTUwLCJhenAiOiJ0QWZwSHFENHNnZVJlMDdxQVoyMFpnQlU0M0tTU0RkZiIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOnVzZXIiLCJlZGl0OnVzZXIiLCJyZWFkOnVzZXIiXX0.ZpQZsAEsJ1LTDCFUd-WT-HLLMmeS4WyGRzq4t8MqrIYPoCMSMtCz-q7N-90vjhTLWpLykMBm3Wb7DyBr0f3y9jiKw53HLOo1eqnLbaQ48cVHX2eWnNdyNhV5K9REDnZaQtynp-EowOWu_a3d5k3wS33H0Zh6ghr3-klW2k6brMizmznlDVxoxfQX7-zt3DOW5BzW9vLChFBVX5hZc2nRwIqbAVF7H5lk6aBF9HZl04HVEdSmMtFGahDxEJ27Lgvl5QTWAc6FnMqaoRM4DsWPd4OJxBzT_e3ONynlwFJRjOf7jyVROJl5pVz-5liyFEMAeIWDb3NbOWSUtXxvETNQRA"
}

class Config(object):
    DEBUG = False
    TESTING = False
    CSRF_ENABLED = True
    SECRET_KEY = 'this-really-needs-to-be-changed'
    SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']


class ProductionConfig(Config):
    DEBUG = False


class StagingConfig(Config):
    DEVELOPMENT = True
    DEBUG = True


class DevelopmentConfig(Config):
    DEVELOPMENT = True
    DEBUG = True


class TestingConfig(Config):
    TESTING = True